# Generated by Django 2.1 on 2019-08-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.CharField(default='', max_length=11, primary_key=True, serialize=False, verbose_name='学号')),
                ('interview_name', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('interview_direction', models.CharField(default='', max_length=15, verbose_name='方向')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='原因')),
            ],
        ),
    ]
