# Generated by Django 2.1.5 on 2019-08-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_password',
            field=models.CharField(default='', max_length=30, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='问题详情'),
        ),
    ]
