# Generated by Django 2.1 on 2019-08-09 02:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freshman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newstudent_id', models.CharField(max_length=11, verbose_name='学号')),
                ('newname', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(max_length=5, verbose_name='性别')),
                ('college', models.CharField(max_length=30, verbose_name='所属学院')),
                ('major', models.CharField(max_length=100, verbose_name='所属专业')),
                ('newclass', models.CharField(max_length=20, verbose_name='班级')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('qq', models.CharField(max_length=15, verbose_name='QQ号')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('direction', models.CharField(choices=[('development', '开发'), ('design', '设计'), ('secretariat', '秘书处')], max_length=15, verbose_name='选择方向')),
                ('appointment_one', models.DateTimeField(blank=True, null=True, verbose_name='预约时间一')),
                ('appointment_two', models.DateTimeField(blank=True, null=True, verbose_name='预约时间二')),
                ('application', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='申请书')),
                ('interview_time', models.DateTimeField(blank=True, null=True, verbose_name='面试时间')),
                ('interview_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='面试地点')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='评分')),
                ('evaluate', models.TextField(blank=True, max_length=300, null=True, verbose_name='评价')),
                ('interview_result', models.CharField(blank=True, choices=[('A_passd', '面试A轮通过'), ('A_failed', '面试A轮失败'), ('B_passd', '面试B轮通过'), ('B_failed', '面试B轮失败')], max_length=50, null=True, verbose_name='面试结果')),
                ('interview_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='面试官')),
            ],
            options={
                'verbose_name': '新生信息',
                'verbose_name_plural': '新生信息',
            },
        ),
    ]
