# Generated by Django 2.1 on 2019-08-16 12:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshman',
            name='application',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='申请书'),
        ),
    ]
